import React from 'react';
import ReactDOM from 'react-dom/client';
import { I18nextProvider } from 'react-i18next';
import { Toaster } from 'react-hot-toast';
import App from './app/App';
import i18n from './i18n';
// Removed WebSocketProvider: NewUI не использует глобальный WS провайдер
import './styles/globals.css';
import './styles/tailwind.css';
import { TOAST_CONFIG } from './shared/utils/constants';

// Register Service Worker (only in production)
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    // Try sw-v3.js first (generated by VitePWA), fallback to sw.js
    navigator.serviceWorker.register('/sw-v3.js')
      .catch(() => navigator.serviceWorker.register('/sw.js'))
      .catch((error) => {
        console.warn('Service worker registration failed:', error);
      });
  });
}

// iOS viewport height fix
const setVH = () => {
  const vh = window.innerHeight * 0.01;
  document.documentElement.style.setProperty('--vh', `${vh}px`);
};

setVH();
window.addEventListener('resize', setVH);
window.addEventListener('orientationchange', setVH);

ReactDOM.createRoot(document.getElementById('root')).render(
  <I18nextProvider i18n={i18n}>
      <App />
    <Toaster {...TOAST_CONFIG} />
  </I18nextProvider>
);

// Vercel trigger
// Force Service Worker update Wed Oct 29 22:09:22 EET 2025
