import React from 'react';
import ReactDOM from 'react-dom/client';
import { I18nextProvider } from 'react-i18next';
import { Toaster } from 'react-hot-toast';
import App from './app/App';
import i18n from './i18n';
// Removed WebSocketProvider: NewUI не использует глобальный WS провайдер
import './styles/globals.css';
import './styles/tailwind.css';
import { TOAST_CONFIG } from './shared/utils/constants';

// Register Service Worker (only in production)
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  // Удаляем ВСЕ старые Service Workers сразу при загрузке скрипта (до load event)
  (async () => {
    try {
      const registrations = await navigator.serviceWorker.getRegistrations();
      for (const registration of registrations) {
        await registration.unregister();
        console.log('🗑️ Unregistered Service Worker:', registration.active?.scriptURL || registration.scope);
      }
    } catch (error) {
      console.warn('Failed to unregister old Service Workers:', error);
    }
  })();

  window.addEventListener('load', async () => {
    // Проверяем доступность файла перед регистрацией
    const registerSW = async (swPath) => {
      try {
        // Сначала проверяем что файл - это JavaScript, не HTML
        const response = await fetch(swPath, { method: 'GET', cache: 'no-cache' });
        const contentType = response.headers.get('content-type');
        const text = await response.text();
        
        // Если файл начинается с HTML, это не Service Worker - пропускаем
        if (text.trim().startsWith('<!') || !contentType?.includes('javascript')) {
          console.warn(`⚠️ Service Worker file ${swPath} is not JavaScript (content-type: ${contentType})`);
          return false;
        }
        
        // Проверяем что это действительно JavaScript код
        if (!text.includes('addEventListener') && !text.includes('self') && !text.includes('serviceWorker')) {
          console.warn(`⚠️ Service Worker file ${swPath} doesn't look like a valid SW`);
          return false;
        }
        
        const registration = await navigator.serviceWorker.register(swPath);
        console.log('✅ Service Worker registered:', swPath, registration);
        return true;
      } catch (error) {
        console.warn(`⚠️ Failed to register ${swPath}:`, error.message);
        return false;
      }
    };
    
    // Try sw-v3.js first (generated by VitePWA), then service-worker.js
    // НЕ используем sw.js - он возвращает HTML
    const success = await registerSW('/sw-v3.js');
    if (!success) {
      console.log('sw-v3.js not available, trying service-worker.js...');
      await registerSW('/service-worker.js');
    }
  });
}

// iOS viewport height fix
const setVH = () => {
  const vh = window.innerHeight * 0.01;
  document.documentElement.style.setProperty('--vh', `${vh}px`);
};

setVH();
window.addEventListener('resize', setVH);
window.addEventListener('orientationchange', setVH);

ReactDOM.createRoot(document.getElementById('root')).render(
  <I18nextProvider i18n={i18n}>
      <App />
    <Toaster {...TOAST_CONFIG} />
  </I18nextProvider>
);

// Vercel trigger
// Force Service Worker update Wed Oct 29 22:09:22 EET 2025
